#--------------------------------------------------------------------------------
# Workflow configuration
#--------------------------------------------------------------------------------

name: "Flatpak build"
on: workflow_dispatch

#--------------------------------------------------------------------------------
# Workflow jobs
#--------------------------------------------------------------------------------

jobs:
  ## GNU/Linux build ###########################################################
  build-flatpak:
    name: "Flatpak build"
    runs-on: ubuntu-20.04
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-21.08
      options: --privileged
    steps:
    - uses: actions/checkout@v2
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
      with:
        bundle: watchflower.flatpak
        manifest-path: assets/linux/watchflower.flatpak.yml
        cache-key: flatpak-builder-${{ github.sha }}
