#-------------------------------------------------------------------------------
# Workflow configuration
#-------------------------------------------------------------------------------

name: "Flatpak build"
on: workflow_dispatch

#-------------------------------------------------------------------------------
# Workflow jobs
#-------------------------------------------------------------------------------

jobs:
  ## GNU/Linux flatpak build ###################################################
  build-flatpak:
    name: "Flatpak build"
    runs-on: ubuntu-20.04
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-22.08
      options: --privileged
    steps:
    - uses: actions/checkout@v3
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
      with:
        bundle: watchflower.flatpak
        manifest-path: assets/linux/watchflower.flatpak.yml
        cache-key: flatpak-builder-${{ github.sha }}
